### ISSUE TITLE
Some notes being visualized but not played

### ISSUE THREAD

**Issue by VG-account1** [cifkao/html-midi-player#19]
Some notes are being visualized but not played. For example the lowest note of the highest voice (purple) of [passport.mid](https://archive.org/download/passport.mid/passport.mid) (mirrors [here](https://midis.fandom.com/wiki/Passport#Listen_to_Midi)).

**Comment by cifkao** [comment]
Interesting. I tried logging the note events and I can see these notes (with pitch 89) in the log, but cannot hear them played. This must be a problem with the sound fonts used by [Magenta.js](https://github.com/magenta/magenta-js) (I can reproduce the issue by uploading the file to [their demo](https://magenta.github.io/magenta-js/music/demos/visualizer.html)), so I suggest you raise the issue there.

**Comment by VG-account1** [comment]
https://github.com/magenta/magenta-js/issues/573

**Comment by cifkao** [comment]
Fixed (`@magenta/music@1.23.1`)! I just updated https://cifkao.github.io/html-midi-player/ and the readme.
