### ISSUE TITLE
Add horizontal scroll for piano-roll visualizer 

### ISSUE THREAD

**Issue by NeroBlackstone** [cifkao/html-midi-player#20]
![Screenshot from 2021-06-22 19-06-21](https://user-images.githubusercontent.com/17470335/122917004-20902100-d390-11eb-9dc0-9e1001fdab1f.png)
Do you mind add a horizontal scroll for piano-roll visualizer? Thanks!

**Comment by cifkao** [comment]
You can make the visualizer scroll by setting `overflow-x: auto` or `overflow-x: scroll` on the `.piano-roll-visualizer` element, i.e.:
```css
.piano-roll-visualizer {
   overflow-x: auto;
}
```
Like here: https://cifkao.github.io/html-midi-player/

**Comment by cifkao** [comment]
I just realized that the staff visualizer does scroll automatically, but the piano roll visualizer doesn't. So you are probably right that I should make the piano roll one scroll to make it consistent.

**Comment by cifkao** [comment]
I just released version 1.3.0-1 (pre-release), you can try if it works for you.
