### ISSUE TITLE
No sound when played on phones.

### ISSUE THREAD

**Issue by reichang182** [cifkao/html-midi-player#28]
When the play button is pressed, the progress bar is moving and notes are highlighted, but no sound is played from the phone. (The same page works well on laptops.)

Device: iPhone XR
Browser: Safari and Chrome

**Comment by majorcyto** [comment]
Hi,

This is working fine for me on my iPhone 12 Pro. This also works on my iPad Pro. Make sure you do not have the 'silence' toggle on the side of the phone on, as it will mute all browser audio.

**Comment by ketanapate** [comment]
We have checked mobile sound also. Also, we have noticed that the MIDI player is not working with Samsung Mobile.

**Comment by majorcyto** [comment]
Still works fine for me.

**Comment by cifkao** [comment]
To anyone experiencing this issue, can you please check other Web Audio demos such as [this](https://mdn.github.io/webaudio-examples/audio-basics/) or [this](https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/Web_Audio_API/Simple_synth/_sample_.The_video_keyboard.html)? If these don't work either, then it's probably a problem with your browser or device and there is no way to fix it here.
