### ISSUE TITLE
Loading Bar

### ISSUE THREAD

**Issue by ireneyrzd** [cifkao/html-midi-player#29]
Is it possible to add a loading bar that shows up when the audio and piano animation is being downloaded and generated?

**Comment by cifkao** [comment]
I implemented an initial version of the shimmer effect on the [`loading`](https://github.com/cifkao/html-midi-player/tree/loading) branch. I still need to add a way to distinguish between a loading state and an error state.

**Comment by cifkao** [comment]
![shimmer](https://user-images.githubusercontent.com/8046580/129070750-1507f9ae-b233-4d22-8816-c1ef6ad3fe41.gif)

**Comment by majorcyto** [comment]
@cifkao - Just saw you put a pre-release test up! Looking forward to this as well as that is one of the main feedback notes I have received is that users are unsure sometimes if it is still loading notes in the background or not. (That and the scroll bar not resetting when replaying something). When the actual release goes on the CDN jsdelivr I will test it and gather feedback. 

I have been working on implementing the project into my existing site and have made some good progress, you can see a [demo here](https://musicalnexus.net/mabinogi/solos/anime/fategrand-order-babylonia-opening-phantom-joke-r4025/).

I have made a custom Soundfont so the note file sizes are a bit bigger than default so this will be a big help for me from a UI/UX Perspective! 

(Now if only we could get Magenta to fix the pitch 89 / 90 issue lol).

**Comment by cifkao** [comment]
@majorcyto I just published a new one. Grab the script here if you would like to try it: https://github.com/cifkao/html-midi-player/releases/download/loading-rc1/midi-player.min.js

> I have been working on implementing this project into my existing site and have made some good progress, you can see a demo [here](https://musicalnexus.net/mabinogi/solos/anime/fategrand-order-babylonia-opening-phantom-joke-r4025/) and [here](https://musicalnexus.net/mabinogi/solos/anime/the-disastrous-life-of-saiki-k-seishun-wa-zankoku-janai-r4015/).

Looks great! You should be able to customize the shimmer effect to your liking via `midi-player::part(loading-overlay)`.

**Comment by cifkao** [comment]
@majorcyto Actually I just pushed it as `1.4.0-0` on NPM/jsdelivr.

**Comment by majorcyto** [comment]
Hey @cifkao - Thanks for the direct mention! I have updated my Demo pages to the new version and the shimmer loading effect works great! I even tested it by 'throttling' my connection through Chrome tools down to like 1mb/s and it worked as expected!

**Comment by cifkao** [comment]
Released in v1.4.0.
