### ISSUE TITLE
Custom Soundfont libraries

### ISSUE THREAD

**Issue by valentijnnieman** [cifkao/html-midi-player#62]
Hi!
I was wondering if there was any more documentation or info on creating Soundfont folders that work with this library. I have a `snes.sf2` file that I've been using locally using `fluidsynth` to run midi output from a model trained on SNES music. I'd love to be able to play them in the browser using this library, since it's so easy to use. I tried running the generator from https://github.com/gleitz/MIDI.js which does create a sort of similar structure, although it's too different from what Magenta uses. Any tips or help would be more than welcome! I realize this might not be the best place to ask for help though, so please feel free to direct me elsewhere!

**Comment by cifkao** [comment]
Hi, this has been discussed in #43.
